language: php

php:
    - 5.4
    - 5.5

before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libevent-dev
    - sudo pecl install -f libevent-beta | true
    - composer install