language: php

php:
    - 5.4
    - 5.5

before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libevent-dev
    - echo -ne '\n' | sudo pecl install -f libevent-beta
    - echo "extension=libevent.so" >> "$(php -r 'echo php_ini_loaded_file();')"
    - composer install